    version: "3"
    services:
      mopidy:
        image: rawdlite/mopidy
        container_name: mopidy
        devices:
          - "/dev/snd"
        ports:
          - "6600:6600"
          - "6680:6680"
        restart: unless-stopped
        volumes:
          - /opt/mopidy/config/:/root/.config/
          - /mnt/nas/music/:/data/music/
      mysql:
        image: linuxserver/mariadb
        restart: unless-stopped
        container_name: mysql
        environment:
          - PUID=1007
          - PGID=1008
          - MYSQL_ROOT_PASSWORD=b4FUk4mF>3As3aA
          - TZ=Europe/Berlin
          - MYSQL_DATABASE=romprdb
          - MYSQL_USER=rompr
          - MYSQL_PASSWORD=romprdbpass
        volumes:
          - /opt/mopidy/db_config:/config
        ports:
          - "3306:3306"
      rompr:
        image: rawdlite/rompr
        container_name: rompr
        restart: always
        ports:
          - "80:80"
