---
version: "2"
services:
  airsonic:
    image: ghcr.io/kagemomiji/airsonic-advanced
    container_name: airsonic-advanced
    restart: unless-stopped
    environment:
      - TZ=America/Denver # e.g. Europe/London
      - PUID=1007 # for UserID
      - PGID=1008 # for GroupID
     # - JAVA_OPTS # For passing additional java options.
     # - CONTEXT_PATH # For setting url-base in reverse proxy setups.
    volumes:
      - /opt/airsonic-advanced/data:/var/airsonic # Configuration file location.
      - playlists:/var/playlists # Location for playlists to be saved to.
      - music:/var/music # Location of music.
      - podcasts:/var/podcasts # Location of podcasts.
#      - /srv/2TB1/Youtube:/var/youtube # Location of other media.
#      - /srv/2TB1/Audio-Books:/var/audio-books
    ports:
      - 4040:4040 # WebUI
    # devices:
      # - /dev/snd:/dev/snd # Only needed to pass your host sound device to Airsonic's Java jukebox player.
volumes:
  music:
    driver: local
    driver_opts:
      type: "nfs4"
      o: "addr=10.0.0.3"
      device: ":/mnt/cache_slow-striped/music"
  playlists:
    driver: local
    driver_opts:
      type: "nfs4"
      o: "addr=10.0.0.3"
      device: ":/mnt/media/misc/playlists"
  podcasts:
    driver: local
    driver_opts:
      type: "nfs4"
      o: "addr=10.0.0.3"
      device: ":/mnt/media/misc/podcasts"
