version: '3'

services:
  reverse-proxy:
    image: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8081:8081"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    networks:
      - web
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker

networks:
  web:
    external: true
