---
version: "2"
services:
  ombi:
    container_name: ombi
    image: linuxserver/ombi
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=America/Denver
      - PUID=1007
      - PGID=1008
      - EAP=1
    ports:
      - 3579:3579
    volumes:
      - /opt/dl/ombi:/config
