---
version: "2"
services:
  ombi:
    container_name: ombi
    image: rogueosb/ombi
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=America/Denver
      - PUID=1007
      - PGID=1007
      - EAP=1
    ports:
      - 5000:5000
    volumes:
      - /opt/dl/ombi:/config