---
version: "2"
services:
  bookstack:
    image: linuxserver/bookstack:latest
    container_name: bookstack
    environment:
      - PUID=1007
      - PGID=1008
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=tacotuesday
      - DB_DATABASE=bookstackapp
      - APP_URL=https://kb.ogbase.net
    volumes:
      - /mnt/opt/dl/bookstacks:/config
      - uploads:/var/www/bookstack/public/uploads
      - storage-uploads:/var/www/bookstack/public/storage
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: linuxserver/mariadb:latest
    container_name: bookstack_db
    environment:
      - PUID=1007
      - PGID=1008
      - MYSQL_ROOT_PASSWORD=tacotuesday
      - TZ=America/Denver
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=tacotuesday
    volumes:
      - mariadb-data:/config
    restart: unless-stopped
volumes:
 mariadb-data:
 uploads:
 storage-uploads:
