version: '3'

services:
  apt-cacher-ng:
    image: sameersbn/apt-cacher-ng
    container_name: apt-cacher-ng
    ports:
      - "3142:3142"
    volumes:
      - /opt/apt-cacher-ng/cache:/var/cache/apt-cacher-ng
      - /opt/apt-cacher-ng/acng.conf:/etc/apt-cacher-ng/acng.conf
    restart: unless-stopped