version: '2.3'

services:
  statping:
    container_name: statping
    image: adamboutcher/statping-ng:latest
    restart: always
    volumes:
      - /opt/statping:/app
    environment:
      DB_CONN: sqlite
    ports:
      - 5756:8080
