---
version: "2.1"
services:
  duplicati:
    image: linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=1007
      - PGID=1008
      - TZ=America/Denver
      - CLI_ARGS= #optional
    volumes:
      - /opt/dl/dubplicati/config:/config
      - /mnt/backup:/backups
      - /:/source
    ports:
      - 8200:8200
    restart: unless-stopped
