# WARNING: Replace the example passwords with secure secrets.
# WARNING: 'my_secret_phpipam_pass' and 'my_secret_mysql_root_pass'

version: '3'

services:
  phpipam-web:
    container_name: phpipam-web
    image: phpipam/phpipam-www:latest
    ports:
      - "5333:80"
    environment:
      - TZ=America/Denver
      - IPAM_DATABASE_HOST=phpipam-mariadb
      - IPAM_DATABASE_PASS=my_secret_phpipam_pass
      - IPAM_DATABASE_WEBHOST=%
      - IPAM_TRUST_X_FORWARDED=true
    restart: always
    volumes:
      - /opt/phpipam/phpipam-logo:/phpipam/css/images/logo
    depends_on:
      - phpipam-mariadb

  phpipam-cron:
    image: phpipam/phpipam-cron:latest
    container_name: phpipam-cron
    environment:
      - TZ=America/Denver
      - IPAM_DATABASE_HOST=phpipam-mariadb
      - IPAM_DATABASE_PASS=my_secret_phpipam_pass
      - SCAN_INTERVAL=1h
    restart: always
    depends_on:
      - phpipam-mariadb

  phpipam-mariadb:
    image: mariadb:latest
    container_name: phpipam-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=my_secret_mysql_root_pass
    restart: always
    volumes:
      - /opt/phpipam/phpipam-db-data:/var/lib/mysql

  # phpipam-agent:
  #   image: pierrecdn/phpipam-agent:latest
  #   container_name: phpipam-agent
  #   restart: always

