---
version: "2.1"
services:
  netbootxyz:
    image: lscr.io/linuxserver/netbootxyz
    container_name: netbootxyz
    environment:
      - PUID=1000
      - PGID=1000
      - MENU_VERSION=1.9.9 #optional
      - PORT_RANGE=30000:30010 #optional
#      - SUBFOLDER=/ #optional if behind subfolder based reverse proxy
    volumes:
      - /opt/netbootxyz/config:/config
      - /opt/netbootxyz/assets:/assets #optional
    ports:
      - 6715:3000 #web interface
      - 69:69/udp
      - 8715:80 #optional NGINX server for hosting assets.
    restart: unless-stopped
