---
version: "2"
services:
  bookstack:
    image: ghcr.io/linuxserver/bookstack:latest
    container_name: bookstack
    environment:
      - PUID=1007
      - PGID=1008
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=tacotuesday
      - DB_DATABASE=bookstackapp
      - APP_URL=https://kb.ogbase.net
      - # AUTH_METHOD=standard # Force standard auth
      - AUTH_METHOD=ldap
      - LDAP_SERVER=ipa1.ogbase.net
      - LDAP_BASE_DN=users,dc=ogbase,dc=net
      - LDAP_DN=false
      - LDAP_PASS=false
      - LDAP_USER_FILTER=(&(uid=$${user}))
      - LDAP_VERSION=3
      - LDAP_ID_ATTRIBUTE=uid
      - LDAP_EMAIL_ATTRIBUTE=mail
      - LDAP_DISPLAY_NAME_ATTRIBUTE=cn
      - LDAP_START_TLS=false
    volumes:
      - /opt/bookstack/config:/config
      - /opt/bookstack/uploads:/var/www/bookstack/public/uploads
      - /opt/bookstack/storage-uploads:/var/www/bookstack/public/storage
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: linuxserver/mariadb:latest
    container_name: bookstack_db
    environment:
      - PUID=1007
      - PGID=1008
      - MYSQL_ROOT_PASSWORD=tacotuesday
      - TZ=America/Denver
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=tacotuesday
    volumes:
      - /opt/bookstack/mariadb-data:/config
    restart: unless-stopped
