---
version: "2"
services:
  sonarr:
    image: linuxserver/sonarr:preview
    container_name: sonarr
    environment:
      - TZ=America/Denver
      - PUID=1007
      - PGID=1008
    volumes:
      - /opt/dl/sonarr_preview:/config
      - /mnt/shows:/tv
      - /mnt/downloads/torrents:/downloads
      - /mnt/anime:/anime   
    ports:
      - 8989:8989
    mem_limit: 4096m
    restart: unless-stopped
