---
version: "2.1"
services:
  emby:
    image: linuxserver/emby
    container_name: emby
    environment:
      - PUID=1006
      - PGID=1007
      - TZ=America/Denver
      - UMASK_SET=<022> #optional
    volumes:
      - /opt/dl/emby:/config
      - /mnt/series:/data/tvshows
      - /mnt/movies:/data/movies
#      - /path/for/transcoding:/transcode #optional
#      - /opt/vc/lib:/opt/vc/lib #optional
    ports:
      - "8096:8096"
      - "8920:8920" #optional
    devices:
#      - /dev/dri:/dev/dri #optional
#      - /dev/vchiq:/dev/vchiq #optional
#      - /dev/video10:/dev/video10 #optional
#      - /dev/video11:/dev/video11 #optional
#      - /dev/video12:/dev/video12 #optional
    restart: unless-stopped