version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=keycloak
      - POSTGRESQL_DATABASE=keycloak
    volumes:
      - ./postgresql_data:/bitnami/postgresql
  keycloak:
    image: docker.io/bitnami/keycloak:latest
    ports:
      - "8771:8080"
      - "8772:8443"
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_ADMIN_USER=${KEYCLOAK_ADMIN_USER:-admin}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD:-admin}
      # WildFly user
      - KEYCLOAK_MANAGEMENT_USER=${KEYCLOAK_MANAGEMENT_USER:-manager}
      - KEYCLOAK_MANAGEMENT_PASSWORD=${KEYCLOAK_MANAGEMENT_PASSWORD:-mpassword}
      - KEYCLOAK_DATABASE_NAME=keycloak
      - KEYCLOAK_DATABASE_USER=${KEYCLOAK_DATABASE_USER:-keycloak}
      - KEYCLOAK_DATABASE_PASSWORD=${KEYCLOAK_DATABASE_PASSWORD:-keycloak}
        #      - KEYCLOAK_ENABLE_HTTPS=true
    depends_on:
      - postgresql
        #    volumes:
        #      - './mynewtheme:/opt/bitnami/keycloak/themes/mynewtheme'
