---
version: "2.1"
services:
  airsonic:
    image: airsonic/airsonic
    container_name: airsonic
    environment:
      - PUID=1007
      - PGID=1008
      - TZ=America/Denver
      - CONTEXT_PATH=airsonic.ogbase.net #optional
#      - JAVA_OPTS=<options> #optional
    volumes:
      - /opt/dl/airsonic:/airsonic/data
      - /mnt/music:/airsonic/music
      - /mnt/misc/playlist:/airsonic/playlists
      - /mnt/misc/podcast:/airsonic/podcasts
#      - </path/to/other media>:/media #optional
    ports:
      - 4040:4040
    restart: unless-stopped
