---
version: '2.1'
services:
    airsonic:
        image: ghcr.io/linuxserver/airsonic
        volumes:
            - '/opt/dl/airsonic-advanced:/config'
            - '/mnt/music:/music'
            - '/mnt/misc/playlists:/playlists'
            - '/mnt/misc/podcasts:/podcasts'
        ports:
            - '4040:4040'
        environment:
        - TZ=America/Denver
        - UID=1007
        - PGID=1008
        restart: always
        container_name: airsonic
