---
version: '3.3'
services:
    airsonic:
        volumes:
            - '/opt/dldata:/airsonic/data'
            - '/mnt/music:/airsonic/music'
            - '/mnt/misc/playlists:/airsonic/playlists'
            - '/mnt/misc/podcasts:/airsonic/podcasts'
        ports:
            - '4040:4040'
        image: airsonic/airsonic
        restart: unless-stopped
        container_name: airsonic