---
version: '3'
services:

  nextcloud-db:
    image: mariadb:10.5.11
    container_name: nextcloud-db
    hostname: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: unless-stopped
    volumes:
      - /opt/nextcloud/nextcloud-data-db:/var/lib/mysql

  nextcloud-redis:
    image: redis:5.0.9-alpine
    container_name: nextcloud-redis
    hostname: nextcloud-redis
    restart: unless-stopped

  nextcloud-app:
    image: nextcloud:fpm-alpine
    container_name: nextcloud-app
    hostname: nextcloud-app
    restart: unless-stopped
    env_file: .env
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    volumes:
      - /opt/nextcloud/nextcloud-data/:/var/www/html
      - /mnt/nextcloud_data/:/var/www/html/data

  nextcloud-web:
    image: nginx:alpine
    container_name: nextcloud-web
    hostname: nextcloud-web
    restart: unless-stopped
    volumes:
      - /opt/nextcloud/nextcloud-data/:/var/www/html:ro
      - /opt/nextcloud/nginx.conf:/etc/nginx/nginx.conf:ro
      - /mnt/nextcloud_data/:/var/www/html/data:ro
    ports:
      - 80:80

  nextcloud-cron:
    image: nextcloud:fpm-alpine
    container_name: nextcloud-cron
    hostname: nextcloud-cron
    restart: unless-stopped
    volumes:
      - /opt/nextcloud/nextcloud-data/:/var/www/html
      - /mnt/nextcloud_data/:/var/www/html/data
    entrypoint: /cron.sh
    depends_on:
      - nextcloud-db
      - nextcloud-redis