---
version: "2.1"
services:
  calibre-web:
    image: lscr.io/linuxserver/mods:universal-calibre
    container_name: calibre-web
    environment:
      - PUID=1007
      - PGID=1008
      - TZ=America/Denver
      - DOCKER_MODS=linuxserver/calibre-web:calibre
      # - DOCKER_MODS=ghcr.io/gilbn/theme.park:calibre-web
      # - TP_THEME=hotline
    volumes:
      - /opt/calibre-web:/config
      - calibre-library:/calibre-library
    ports:
      - 8783:8083
    restart: unless-stopped
volumes:
  calibre-library:
    driver: local
    driver_opts:
      type: "nfs4"
      o: "addr=10.0.0.3"
      device: ":/mnt/media/misc/calibre-library"
