---
version: "2.1"
services:
  calibre-web:
    image: ghcr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1007
      - PGID=1008
      - TZ=America/Denver
      - DOCKER_MODS=linuxserver/calibre-web:calibre
      # - DOCKER_MODS=ghcr.io/gilbn/theme.park:calibre-web
      # - TP_THEME=hotline
    volumes:
      - /opt/calibre-web:/config
      - /mnt/misc/calibre-library:/calibre-library
    ports:
      - 8783:8083
    restart: unless-stopped
