--- 
web: 
  environment: 
    GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.ogbase.net'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
  hostname: gitlab.ogbase.net
  image: "gitlab/gitlab-ee:latest"
  ports: 
    - "8929:8929"
    - "2224:22"
  restart: always
  volumes: 
    - "$GITLAB_HOME/config:/etc/gitlab"
    - "$GITLAB_HOME/logs:/var/log/gitlab"
    - "$GITLAB_HOME/data:/var/opt/gitlab"
