---
web:
  image: gitlab/gitlab-ce:latest
  restart: always
  hostname: 'gitlab.ogbase.net'
  container_name: gitlab
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      gitlab_rails['gitlab_shell_ssh_port'] = 2224
  ports:
    - '8929:80'
    - '2224:22'
  volumes:
    - '/opt/dl/gitlab/config:/etc/gitlab'
    - '/opt/dl/gitlab/logs:/var/log/gitlab'
    - '/opt/dl/gitlab/data:/var/opt/gitlab'
