version: '3.3'
services:
    code:
        ports:
            - '9980:9980'
        environment:
            - username=cupric
            - password=secret
            - TZ=America/Denver
            - domain=nextcloud.ogbase.net
            - VIRTUAL_HOST=asimov.ogbase.net
            - VIRTUAL_PORT=9980
            - VIRTUAL_PROTO=https
#        volumes:
#          - /opt/dl/collabora/config:/etc/loolwsd
        cap_add:
            - MKNOD
        restart: always
        image: collabora/code
