version: '3.3'
services:
    code:
        ports:
            - '9980:9980'
        environment:
            - domain=collabora\\.ogbase\\.net
            - username=cupric
            - password=secret
        volumes:
          - /opt/dl/collabora/config:/etc/loolwsd
        environment:
          - TZ=America/Denver
          - PUID=1007
          - PGID=1008
          - domain=nextcloud.ogbase.net
        cap_add:
            - MKNOD
        restart: always
        image: collabora/code
