---
version: "2"
services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - TZ=America/Denver
      - PUID=1007
      - PGID=1008
    volumes:
      - /opt/dl/jackett:/config
      - /opt/downloads/blackhole:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
