---
version: "2"
services:
  sonarr:
    image: linuxserver/jackett
    container_name: radarr
    environment:
      - TZ=America/Denver
      - PUID=1007
      - PGID=1008
    volumes:
      - /opt/dl/jackett:/config
      - /opt/downloads/blackhole:/downloads
    ports:
      - 9117:9117
    mem_limit: 4096m
    restart: unless-stopped