version: '3.3'
services:
    idrac6:
        ports:
            - '5800:5800'
            - '5900:5900'
        environment:
            - IDRAC_HOST=idrac.ogbase.net
            - IDRAC_USER=root
            - IDRAC_PASSWORD=Polar2000
        image: domistyle/idrac6
        restart: always
        container_name: idrac
