---
version: "2.1"
services:
  remotely:
    image: translucency/remotely:latest
    container_name: remotely
    ports:
      - 5000:5000
    volumes:
      - /opt/remotely/data:/remotely-data
networks:
  default:
    name: rp-net
