---
version: "2.1"
services:
  remotely:
    image: translucency/remotely:latest
    container_name: remotely
    ports:
      - 5222:5000
    volumes:
      - /opt/dl/remotely:/remotely-data
networks:
  default:
    name: rp-net