version: "2"
services:
  remotely:
    image: translucency/remotely:latest
    container_name: remotely
    ports:
      - 5222:5000
    volumes:
      - /remotely-data:/remotely-data
networks:
  default:
    name: rp-net