---
version: "3"
services:
  gluetun:
    container_name: gluetun-vpn
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=privado
      - OPENVPN_USER=${USERNAME}
      - OPENVPN_PASSWORD=${PASSWORD}
      - SERVER_COUNTRIES=Netherlands
