---
version: "2.1"
services:
  calibre:
    image: ghcr.io/linuxserver/calibre
    container_name: calibre
    environment:
      - PUID=1007
      - PGID=1008
      - TZ=America/Denver
        #- PASSWORD= password
        #- CLI_ARGS= #optional
    volumes:
      - /opt/dl/calibre/config:/config
      - /mnt/misc/calibre-library:/calibre-library
      - /opt/dl/calibre/uploads:/uploads
    ports:
      - 8780:8080
      - 8781:8081
    restart: unless-stopped
