---
version: "2.1"
services:
  calibre:
    image: ghcr.io/linuxserver/calibre
    container_name: calibre
    environment:
      - PUID=1007
      - PGID=1008
      - TZ=America/Denver
        #- PASSWORD= password
        #- CLI_ARGS= #optional
    volumes:
      - /opt/calibre/config:/config
      - calibre-library:/calibre-library
      - /opt/uploads:/uploads
    ports:
      - 8780:8080
      - 8781:8081
    restart: unless-stopped
volumes:
  calibre-library:
    driver: local
    driver_opts:
      type: "nfs4"
      o: "addr=10.0.0.3"
      device: ":/mnt/media/misc/calibre-library"

