---
version: '3'

services:
  bitwarden:
    image: bitwardenrs/server
    container_name: bitwarden
    restart: always
    volumes:
      - /opt/dl/bitwarden:/data
    environment:
      WEBSOCKET_ENABLED: 'true' # Required to use websockets
      SIGNUPS_ALLOWED: 'false'   # set to false to disable signups
      ADMIN_TOKEN: 'VN6f75wzCtJ7As5qVCSDETKtQbPw93AQgaLge2VxHuphkBChze'
    ports:
      - "8004:80"