---
version: "2.1"
services:
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: host
    environment:
      - PUID=1007
      - PGID=1008
      - TZ=America/Denver
      - UMASK_SET=022 #optional
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /opt/dl/deluge/config:/config
      - /mnt/downloads:/downloads
    restart: unless-stopped