---
version: "2.1"
services:
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: host
    environment:
      - PUID=1007
      - PGID=1008
      - TZ=America/Denver
      - UMASK_SET=022 #optional
      - DELUGE_LOGLEVEL=error #optional
      - AUTO_UPDATE=true #optional
    volumes:
      - /opt/dl/deluge:/config
      - /mnt/downloads:/downloads
    ports:
      - 8112:80
      - 6881:6881
    restart: unless-stopped
