---
# You need to create the network 'porn-vault-net'

# Container will fail on first start - need to add to config file
# {
#   "search": {
#     "host": "http://<name of elasticsearch docker container:9200",
#     "version": "7.x",
#     "log": false
#   },

version: "3"
services:
  porn-vault:
    image: leadwolf/porn-vault:latest
    container_name: porn-vault
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/pvault/config:/config"
      - "/mnt/pvideos:/videos"
      - "/mnt/pimages:/images"
    ports:
      - "3000:3000"
    devices: # Only for vaapi users
      - /dev/dri/renderD128:/dev/dri/renderD128
    restart: always
    networks: # When you run Elasticsearch with Docker
      - porn-vault-net
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.13.1'
    container_name: pv-elasticsearch
    environment:
        - discovery.type=single-node
    ports:
        - '9200:9200'
        - '9300:9300'
    networks:
      - porn-vault-net
networks:
  porn-vault-net:
    driver: bridge
