version: '3.3'
services:
    organizr-v2:
        container_name: organizr
        volumes:
            - /opt/dl/organizr:/config
        environment:
            - PUID=1007
            - PGID=1008
        ports:
            - 5555:80
        image: organizrtools/organizr-v2
        restart: unless-stopped
