version: '3.3'
services:
    organizr-v2:
        container_name: organizr
        volumes:
            - /opt/dl/organizr:/config
        environment:
            - PGID=1000
            - PUID=1000
        ports:
            - '5555:5555'
        image: organizrtools/organizr-v2
