---
version: '3.3'
services:
    truecommand:
        volumes:
            - '/opt/truecommand/data:/data'
        ports:
            - '8001:80'
            - '8002:443'
        restart: unless-stopped
        container_name: truecommand
        environment:
            - TZ=America/Denver
        image: ixsystems/truecommand:latest