version: '2'
services:
    rutorrent:
      image: romancin/rutorrent-flood:latest
      container_name: rutorrent
      networks:
        - default
      tty: true
      volumes:
        - /opt/dl/rutorrent:/config
        - /mnt/downloads:/downloads
      environment:
        - PUID=1010
        - PGID=1010
        - TZ=America/Denver
        - CREATE_SUBDIR_BY_TRACKERS=NO
        - SSL_ENABLED=NO
#        - RT_TOKEN=
#        - RT_MASTERS=
      ports:
        - "8112:80"
        - "32316:52316"
        - "3000:3000"
        - "60881:60881"
        - "51415-51415:51415-51415"
