---
version: "2"

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    environment:
      - TZ=America/Denver
      - PUID=$docker_run_user
      - PGID=$docker_run_group
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data

volumes:
  portainer_data:
