---
version: "2"

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    environment:
      - TZ=America/Denver
      - PUID=1010
      - PGID=1010
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/dl/portainer:/data

volumes:
  portainer_data:
