---
version: "2"

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    environment:
      - TZ=${TIMEZONE:-America/New_York}
      - PUID=${DOCKER_RUN_USER:-6006}
      - PGID=${DOCKER_RUN_GROUP:-6006}
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data

volumes:
  portainer_data:
