---
version: "2.1"
services:
  lidarr:
    image: ghcr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1007
      - PGID=1008
      - TZ=America/Denver
      # - DOCKER_MODS=ghcr.io/gilbn/theme.park:lidarr
      # - TP_THEME=hotline
    volumes:
      - /opt/lidarr/config:/config
      - music:/media/music
      - downloads:/data/downloads
      # - /mnt/imports:/media/imports
    ports:
      - 8686:8686
    restart: unless-stopped
volumes:
  downloads:
    driver: local
    driver_opts:
      type: "nfs4"
      o: "addr=10.0.0.3"
      device: ":/mnt/cache_slow-striped/downloads"
  music:
    driver: local
    driver_opts:
      type: "nfs4"
      o: "addr=10.0.0.3"
      device: ":/mnt/cache_slow-striped/music"
