version: "2.1"
services:
  couchdb:
    image: couchdb:{image_version:-latest}
    container_name: obsidian-livesync
    user: "${DUID:-6006}:${DGID:-6006}"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD:-password}
    volumes:
      - /opt/obsidian-livesync/couchdb/data:/opt/couchdb/data
      - /opt/obsidian-livesync/couchdb/etc:/opt/couchdb/etc/local.d
    ports:
      - 5984:5984
    restart: unless-stopped
