version: "2.1"
services:
  couchdb:
    image: couchdb:latest
    container_name: obsidian-livesync-couchdb
    user: "${DUID:-6006}:${DGID:-6006}"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD:-password}
    volumes:
      - /opt/couchdb/data:/opt/couchdb/data
      - /opt/couchdb/etc:/opt/couchdb/etc/local.d
    ports:
      - 5984:5984
    restart: unless-stopped
