version: "2.1"
services:
  couchdb:
    image: couchdb
    container_name: obsidian-livesync
    user: "${UID:-6006}:${GID:-6006}"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD:-password}
    volumes:
      - ./data:/opt/couchdb/data
      - ./local.ini:/opt/couchdb/etc/local.ini
    ports:
      - 5984:5984
    restart: unless-stopped
