version: "2.4"

volumes:
    db:

services:

  freshrss:
    image: freshrss/freshrss:latest
    # Optional build section if you want to build the image locally:
    build:
      # Pick #latest (stable release) or #edge (rolling release) or a specific release like #1.21.0
      context: https://github.com/FreshRSS/FreshRSS.git#latest
      dockerfile: Docker/Dockerfile
    container_name: freshrss
    user: "${DUID:-6006}:${DGID:-6006}"
    hostname: freshrss
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - ./data:/var/www/FreshRSS/data
      - ./extensions:/var/www/FreshRSS/extensions
    environment:
      TZ: America/New_York
      CRON_MIN: '3,33'
    ports:
      - "${PUBLISHED_PORT}:${LISTEN:-80}"
      # Optional parameter, set to 1 to enable OpenID Connect (only available in our Debian image)
      # Requires more environment variables. See https://freshrss.github.io/FreshRSS/en/admins/16_OpenID-Connect.html

  freshrss-db:
    image: postgres:15
    container_name: freshrss-db
    user: "${DUID:-6006}:${DGID:-6006}"
    hostname: freshrss-db
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_BASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    command:
      # Examples of PostgreSQL tuning.
      # https://wiki.postgresql.org/wiki/Tuning_Your_PostgreSQL_Server
      # When in doubt, skip and stick to default PostgreSQL settings.
      - -c
      - shared_buffers=1GB
      - -c
      - work_mem=32MB

  rss-bridge:
    image: rssbridge/rss-bridge:latest
    user: "${DUID:-6006}:${DGID:-6006}"
    volumes:
      - ./rss-bridge/config:/config
      # Cache Folder 
      # Needs to be owned by www-data:www-data
      - ./rss-bridge/cache:/app/cache
    ports:
      - "${RSS_BRIDGE_PUBLISHED_PORT}:80"
    restart: unless-stopped

  morss:
    image: pictuga/morss
    ports:
      - "${MORSS_PUBLISHED_PORT}:8000"
