version: "2.4"

volumes:
    db:

services:

  freshrss:
    image: freshrss/freshrss:latest
    # Optional build section if you want to build the image locally:
    build:
      # Pick #latest (stable release) or #edge (rolling release) or a specific release like #1.21.0
      context: https://github.com/FreshRSS/FreshRSS.git#latest
      dockerfile: Docker/Dockerfile
    container_name: freshrss
    hostname: freshrss
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - ./data:/var/www/FreshRSS/data
      - ./extensions:/var/www/FreshRSS/extensions
    environment:
      TZ: America/New_York
      CRON_MIN: '3,33'
    ports:
      - "${PUBLISHED_PORT}:${LISTEN:-80}"
      # Optional parameter, set to 1 to enable OpenID Connect (only available in our Debian image)
      # Requires more environment variables. See https://freshrss.github.io/FreshRSS/en/admins/16_OpenID-Connect.html
    OIDC_ENABLED:
    FRESHRSS_INSTALL: |-
      --api_enabled
      --base_url ${BASE_URL}
      --db-base ${DB_BASE}
      --db-host ${DB_HOST}
      --db-password ${DB_PASSWORD}
      --db-type pgsql
      --db-user ${DB_USER}
      --default_user admin
      --language en
    FRESHRSS_USER: |-
      --api_password ${ADMIN_API_PASSWORD}
      --email ${ADMIN_EMAIL}
      --language en
      --password ${ADMIN_PASSWORD}
      --user admin

  freshrss-db:
    image: postgres:15
    container_name: freshrss-db
    hostname: freshrss-db
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_BASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    command:
      # Examples of PostgreSQL tuning.
      # https://wiki.postgresql.org/wiki/Tuning_Your_PostgreSQL_Server
      # When in doubt, skip and stick to default PostgreSQL settings.
      - -c
      - shared_buffers=1GB
      - -c
      - work_mem=32MB
