version: "3.6"
services:
  mosquitto-mqtt:
    container_name: mosquitto-mqtt
    networks:
      - frigate
    ports:
      - '1883:1883'
      - '9001:9001'
    image: eclipse-mosquitto
    volumes:
      - /opt/frigatenvr/mqtt:/mosquitto
    restart: unless-stopped 

  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.12.0-beta3
    networks:
      - frigate
    depends_on:
      - mosquitto-mqtt
    shm_size: "128mb" # update for your cameras based on calculation above
    devices:
      # - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /opt/frigatenvr/config/config.yml:/config/config.yml:ro
      - media:/media/frigate
      - /opt/frigatenvr/db:/db
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "frigate"
volumes:
  media:
    driver: local
    driver_opts:
      type: "nfs4"
      o: "addr=10.0.0.3"
      device: ":/mnt/media/surveillance"
networks:
  frigate:
 


