---
version: "2.1"
services:
  lazylibrarian:
    image: ghcr.io/linuxserver/lazylibrarian:latest
    container_name: lazylibrarian
    environment:
      - PUID=1007
      - PGID=1008
      - TZ=America/Denver
      - DOCKER_MODS=linuxserver/calibre-web:calibre|linuxserver/mods:lazylibrarian-ffmpeg #optional
    volumes:
      - /opt/dl/lazylibrarian:/config
      - /mnt/downloads:/downloads
      - /mnt/misc/books:/books
      - /mnt/misc/audiobooks:/audiobooks
    ports:
      - 5299:5299
    restart: unless-stopped
