---
version: "2"
services:
  transmission:
    container_name: transmission
    image: dperson/transmission
    environment:
      - TZ=America/Denver
      - TR_IDLE_SEEDING_LIMIT_ENABLED=true
      - TR_IDLE_SEEDING_LIMIT=600
      - TR_RATIO_LIMIT_ENABLED=true
      - TR_RATIO_LIMIT=4
      - TR_DOWNLOAD_DIR=/downloads
      - TR_INCOMPLETE_DIR_ENABLED=false
      - TR_RENAME_PARTIAL_FILES=true
      - TR_DHT_ENABLED=false
      - TR_PEX_ENABLED=false
      - USERID=1007
      - GROUPID=1007
    volumes:
      - /opt/dl/transmission:/var/lib/transmission-daemon/info
      #set transmission or sonarr download folder to /downloads
      - /mnt/downloads/torrents/complete:/downloads
      - /mnt/downloads/torrents/:/var/lib/transmission-daemon/incomplete
    restart: unless-stopped
