---
version: "2"
services:
  ombi4:
    container_name: ombi4
    image: hotio/ombi:testing
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=America/Denver
      - PUID=1007
      - PGID=1008
      - EAP=1
    ports:
      - 3579:3579
    volumes:
      - /opt/dl/ombi:/config
