 version: '2'
 services:
   db:
     image: mariadb
     env_file:
       - MySQL.env
     volumes:
       - ./datadir:/var/lib/mysql
   shinobi:
     image: migoller/shinobidocker:microservice-alpine
     env_file:
       - MySQL.env
       - Shinobi.env
     volumes:
       - /etc/localtime:/etc/localtime:ro
       - /etc/timezone:/etc/timezone:ro
       - /opt/shiobinvr/config:/config
       - /mnt/media/Shinobi:/opt/shinobi/videos
       - /dev/shm/shinobiDockerTemp:/dev/shm/streams
     ports:
       - "8080:8080"
